package com.example.final_project_android;

public class Inspection_Request_class {

    // Unique ID for the request generated by Firebase
    private String request_uid;

    // Restaurant details matching Restaurant_class fields
    private String business_id;
    private String res_name;
    private String address;
    private String requested_date;

    // Inspector details matching inspector_class fields
    // These will be null until an inspector accepts the request
    private String inspector_id;
    private String inspection_time;

    // Empty constructor required for Firebase
    public Inspection_Request_class() {
    }

    // Constructor for creating a new request from the Restaurant side
    public Inspection_Request_class(String request_uid, String business_id, String res_name, String address, String requested_date) {
        this.request_uid = request_uid;
        this.business_id = business_id;
        this.res_name = res_name;
        this.address = address;
        this.requested_date = requested_date;

        // Initialize as null since no inspector has been assigned yet
        this.inspector_id = "";
        this.inspection_time = "";
    }

    // --- Getters and Setters ---

    public String getRequest_uid() {
        return request_uid;
    }

    public void setRequest_uid(String request_uid) {
        this.request_uid = request_uid;
    }

    public String getBusiness_id() {
        return business_id;
    }

    public void setBusiness_id(String business_id) {
        this.business_id = business_id;
    }

    public String getRes_name() {
        return res_name;
    }

    public void setRes_name(String res_name) {
        this.res_name = res_name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getRequested_date() {
        return requested_date;
    }

    public void setRequested_date(String requested_date) {
        this.requested_date = requested_date;
    }

    public String getInspector_id() {
        return inspector_id;
    }

    public void setInspector_id(String inspector_id) {
        this.inspector_id = inspector_id;
    }

    public String getInspection_time() {
        return inspection_time;
    }

    public void setInspection_time(String inspection_time) {
        this.inspection_time = inspection_time;
    }
}