package com.example.final_project_android;

import java.util.List;

public class Inspection_Report_class {

    // Unique ID for the report generated by Firebase
    private String report_id;

    // Identification details
    private String business_id;
    private String inspector_id;

    // Report
    private String restaurant_name;
    private String date;

    // Scoring details
    private int total_score;
    private String final_grade;

    // List of specific inspection items
    private List<new_inspection_item> inspection_items_list;

    public Inspection_Report_class() {
    }

    // Full constructor for creating a new report
    public Inspection_Report_class(String report_id, String business_id, String inspector_id, String restaurant_name, String date, int total_score, String final_grade, List<new_inspection_item> inspection_items_list) {
        this.report_id = report_id;
        this.business_id = business_id;
        this.inspector_id = inspector_id;
        this.restaurant_name = restaurant_name;
        this.date = date;
        this.total_score = total_score;
        this.final_grade = final_grade;
        this.inspection_items_list = inspection_items_list;
    }

    // Getters and Setters

    public String getReport_id() {
        return report_id;
    }

    public void setReport_id(String report_id) {
        this.report_id = report_id;
    }

    public String getBusiness_id() {
        return business_id;
    }

    public void setBusiness_id(String business_id) {
        this.business_id = business_id;
    }

    public String getInspector_id() {
        return inspector_id;
    }

    public void setInspector_id(String inspector_id) {
        this.inspector_id = inspector_id;
    }

    public String getRestaurant_name() {
        return restaurant_name;
    }

    public void setRestaurant_name(String restaurant_name) {
        this.restaurant_name = restaurant_name;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public int getTotal_score() {
        return total_score;
    }

    public void setTotal_score(int total_score) {
        this.total_score = total_score;
    }

    public String getFinal_grade() {
        return final_grade;
    }

    public void setFinal_grade(String final_grade) {
        this.final_grade = final_grade;
    }

    public List<new_inspection_item> getInspection_items_list() {
        return inspection_items_list;
    }

    public void setInspection_items_list(List<new_inspection_item> inspection_items_list) {
        this.inspection_items_list = inspection_items_list;
    }
}